// me
export const REQUEST_LOG_IN = 'REQUEST_LOG_IN';
export const RECEIVE_LOG_IN = 'RECEIVE_LOG_IN';
export const LOG_OUT = 'LOG_OUT';

// router
export const HISTORY_NAVIGATION = 'HISTORY_NAVIGATION';
export const GO_TO_PAGE_START = 'GO_TO_PAGE_START';
export const GO_TO_PAGE_FINISH = 'GO_TO_PAGE_FINISH';
export const REPLACE_PAGE = 'REPLACE_PAGE';

// services
export const FETCH_SERVICES_REQUEST = 'FETCH_SERVICES_REQUEST';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';
export const FETCH_SERVICES_FAILURE = 'FETCH_SERVICES_FAILURE';
export const EDIT_SERVICE = 'EDIT_SERVICE';
export const ADD_SERVICE = 'ADD_SERVICE';

// tasks
export const FETCH_TASKS_REQUEST = 'FETCH_TASKS_REQUEST';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const ADD_TASK = 'ADD_TASK';
export const EDIT_TASK = 'EDIT_TASK';
export const DELETE_TASK = 'DELETE_TASK';

export const SET_TASKS_SERVICES_FILTER = 'SET_TASKS_SERVICES_FILTER'; //TODO: refactor
export const SET_TASKS_STATUS_FILTER = 'SET_TASKS_STATUS_FILTER'; //TODO: refactor
export const SET_TASKS_DATE_FILTER = 'SET_TASKS_DATE_FILTER'; //TODO: refactor

// users
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const SET_USERS_FILTER = 'SET_USERS_FILTER';

// houses
export const FETCH_HOUSES_REQUEST = 'FETCH_HOUSES_REQUEST';
export const FETCH_HOUSES_SUCCESS = 'FETCH_HOUSES_SUCCESS';
export const FETCH_HOUSES_FAILURE = 'FETCH_HOUSES_FAILURE';
export const SET_HOUSES_FILTER = 'SET_HOUSES_FILTER';
